#!/bin/bash

# Definisi Warna
MERAH='\033[0;31m'
HIJAU='\033[0;32m'
KUNING='\033[1;33m'
BIRU='\033[0;34m'
NC='\033[0m' # No Color (Reset)

while true; do
    clear
    echo -e "${BIRU}=====================================${NC}"
    echo -e "${KUNING}      ZOTERO & LIBREOFFICE MENU      ${NC}"
    echo -e "${BIRU}=====================================${NC}"
    echo -e "${HIJAU}1.${NC} Install Libre + Zotero"
    echo -e "${HIJAU}2.${NC} Cara hubungkan Libre dan Zotero"
    echo -e "${MERAH}3.${NC} Exit"
    echo -e "${BIRU}=====================================${NC}"
    
    read -p "Pilih menu [1-3]: " pilihan

    case $pilihan in
        1)
            wget -O - https://raw.githubusercontent.com/panjiades/Zotero/refs/heads/main/install | bash
            echo -e "${HIJAU}Selesai! Tekan Enter untuk kembali.${NC}"
            read
            ;;
        2)
            
            xdg-open "https://wps-pclevel.blogspot.com/2025/12/cara-menghubungkan-libre-dengan-zotero.html?m=1" 2>/dev/null || sensible-browser "https://wps-pclevel.blogspot.com/2025/12/cara-menghubungkan-libre-dengan-zotero.html?m=1"
            sleep 2
            ;;
        3)
            exit 0
            ;;
        *)
            echo -e "\n${MERAH}Pilihan tidak valid!${NC} Silakan pilih 1, 2, atau 3."
            sleep 2
            ;;
    esac
done
