#!/bin/bash

cd /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/home/user2/

wget https://raw.githubusercontent.com/panjiades/Zotero/refs/heads/main/Zotero-8.0-beta.23.part00

wget https://raw.githubusercontent.com/panjiades/Zotero/refs/heads/main/Zotero-8.0-beta.23.part01

wget https://raw.githubusercontent.com/panjiades/Zotero/refs/heads/main/Zotero-8.0-beta.23.part02

wget https://raw.githubusercontent.com/panjiades/Zotero/refs/heads/main/Zotero-8.0-beta.23.part03

cat Zotero-8.0-beta.23.part* > Zotero-8.0-beta.23.tar.bz2

tar -xvf Zotero-8.0-beta.23.tar.bz2

rm  Zotero-8.0-beta*

cd

proot-distro login debian --user user2 --shared-tmp -- bash -c "cd; cd Zotero_linux-arm64; chmod +x zotero; chmod +x zotero-bin; "
